runtime: php55
api_version: 1
threadsafe: true


handlers:
- url: /assets
  static_dir: assets
  
- url: /assets/custom/img
  static_dir: /assets/custom/img
  
- url: /blog/articles
  static_dir: /blog/articles  
  
- url: /blog/img
  static_dir: /blog/img
  
- url: /blog/index(.*)?
  script: /blog/index.php
  
- url: /blog/article(.*)?
  script: /blog/article.php
  
- url: /blog/(.*)?
  script: /blog/index.php  
  
  
    
  
- url: (.*)?
  static_files: index.html
  upload: index.html
  
  




